name: CI/CD

on:
  push:
    branches: ["**"]      # runs on all branches
  pull_request:
    branches: ["**"]

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' && secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: main
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show project tree (debug)
        run: |
          pwd
          ls -la
          echo "--- main/ ---"
          ls -la main

      - name: Run tests
        working-directory: main
        run: python -m pytest -q

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (and optionally push) Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./main
          push: ${{ env.PUSH_IMAGE == 'true' }}
          tags: ${{ env.PUSH_IMAGE == 'true'
            && format('{0}/flask-lab-project:latest', secrets.DOCKERHUB_USERNAME)
            || 'local/flask-lab-project:latest' }}
